### ISSUE TITLE
File LICENSE absents

### ISSUE THREAD

**Issue by vazhnov** [AndersBNielsen/Universal-Serial-Adapter#4]
Hello!

I found this project from https://hackaday.com/2024/12/25/break-me-off-a-piece-of-that-open-source-serial-adapter/

I see a phrase "Licensed under an open-source hardware license, encouraging collaboration and adaptation" in the README, but I can't find the license information in the repository.

Also I see a comment in `hardware/RS232-USB-C.kicad_sch`:
> License: https://creativecommons.org/licenses/by-sa/4.0/

Could you please create the `LICENSE` file? (it is possible to generate it with "Add file" button, which is located near green "<> Code" button)

**Comment by AndersBNielsen** [comment]
commit 3e01764795425fdef7adac4ed61f9a98ba00f130

**Comment by vazhnov** [comment]
@AndersBNielsen, thank you!
